# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - recommendationsystems

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # - name: Set up virtual environment
      # run: |
      #     python -m venv venv
      #     source venv/bin/activate
      # shell: bash
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python src/components/data_ingestion.py 
    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    # - name: Run Python script
    #   run: python src/components/data_ingestion.py 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dockerharly.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fea08d03a33b42419b2deb1816adfced }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ec5b38f5e0014be7b1cff057082c6425 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dockerharly.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fea08d03a33b42419b2deb1816adfced }}/mlrecom:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'recommendationsystems'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5c236359e30c4cc9a2c013c79071e33b }}
        images: 'dockerharly.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fea08d03a33b42419b2deb1816adfced }}/mlrecom:${{ github.sha }}'